# Creating a Vector

In [5]:
#Use NumPy to create a one-dimensional array:
# Load library

import numpy as np
# Create a vector as a row
vector_row = np.array([1, 2, 3])
print(vector_row)


# Create a vector as a column
print(" ")
vector_column = np.array([[1],
                          [2],
                          [3]])
print(vector_column)

[1 2 3]
 
[[1]
 [2]
 [3]]


# Creating a Matrix

In [6]:
#Use NumPy to create a two-dimensional array:
# Load library

import numpy as np
# Create a matrix
matrix = np.array([[1, 2],
 [1, 2],
 [1, 2]])

print(matrix)

[[1 2]
 [1 2]
 [1 2]]


# Creating a Sparse Matrix


In [8]:
#Create a sparse matrix:
# Load libraries

import numpy as np
from scipy import sparse
# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

# Create compressed sparse row (CSR) matrix

matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


- Sparse matrices only store nonzero elements and assume all other values will be zero,
 leading to significant computational savings. In our solution, we created a NumPy
array with two nonzero values, then converted it into a sparse matrix. If we view the
sparse matrix we can see that only the nonzero values are stored:

- There are a number of types of sparse matrices. However, in compressed sparse row
(CSR) matrices, (1, 1) and (2, 0) represent the (zero-indexed) indices of the nonzero values 1 and 3, respectively. For example, the element 1 is in the second row and
second column. We can see the advantage of sparse matrices if we create a much
larger matrix with many more zero elements and then compare this larger matrix with our original sparse matrix:


In [10]:
# Create larger matrix

matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix

matrix_large_sparse = sparse.csr_matrix(matrix_large)

# View original sparse matrix

print(matrix_sparse)
 

  (1, 1)	1
  (2, 0)	3


# Selecting Elements

In [11]:
#NumPy’s arrays make that easy:
# Load library

import numpy as np
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [12]:
# Select third element of vector

print(vector[2])

3


In [13]:
# Select second row, second column

matrix[1,1]

5

In [16]:
# Select all elements of a vector
print(vector[:])
# Select everything up to and including the third element
print(vector[:3])
# Select everything after the third element
print(vector[3:])
# Select the last element
print(vector[-1])

[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6


In [17]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# Select all rows and the second column
matrix[:,1:2]


array([[2],
       [5],
       [8]])

# Describing a Matrix

- You want to describe the shape, size, and dimensions of the matrix.

In [19]:
#Use shape, size, and ndim:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [20]:
# View number of rows and columns
matrix.shape

(3, 4)

In [21]:
# View number of elements (rows * columns)
matrix.size


12

In [22]:
# View number of dimensions
matrix.ndim

2

# Applying Operations to Elements

- You want to apply some function to multiple elements in an array.


In [31]:
#Use NumPy’s vectorize:
# Load library

import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [32]:
# Create function that adds 100 to something
add_100 = lambda i: i + 100
add_100

<function __main__.<lambda>(i)>

In [33]:
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
print(vectorized_add_100)

In [34]:
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [35]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# Finding the Maximum and Minimum Values

In [38]:
# Load library
import numpy as np
# Create matrix

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Return maximum element
max = np.max(matrix)
print(max)
print()

# Return minimum element
min=np.min(matrix)
print(min)

9

1


In [39]:
# Find maximum element in each column
max = np.max(matrix, axis=0)
print(max)
print()

# Find maximum element in each row
min = np.max(matrix, axis=1)
print(min)

[7 8 9]

[3 6 9]


# Calculating the Average, Variance, and Standard Deviation

In [41]:
#Use NumPy’s mean, var, and std:
# Load library
import numpy as np
# Create matrix

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [42]:
# Return mean
np.mean(matrix)

5.0

In [43]:
# Return variance
np.var(matrix)

6.666666666666667

In [44]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [45]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

# Reshaping Arrays

- You want to change the shape (number of rows and columns) of an array without
changing the element values

In [47]:
#Use NumPy’s reshape:
# Load library
import numpy as np
# Create 4x3 matrix

matrix = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

In [48]:
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [49]:
matrix.size

12

In [50]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [51]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transposing a Vector or Matrix

In [52]:
#Use the T method:
# Load library
import numpy as np
# Create matrix

matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [53]:
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [54]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [55]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Flattening a Matrix

- You need to transform a matrix into a one-dimensional array.

In [56]:
#Use flatten:
# Load library
import numpy as np
# Create matrix

matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [57]:
# Flatten matrix
matrix.flatten()


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

- flatten is a simple method to transform a matrix into a one-dimensional array.
Alternatively, we can use reshape to create a row vector:


In [59]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Finding the Rank of a Matrix

In [60]:
#Use NumPy’s linear algebra method matrix_rank:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 1, 1],
                 [1, 1, 10],
                 [1, 1, 15]])

In [61]:
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

# Calculating the Determinant

In [62]:
#Use NumPy’s linear algebra method det:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])

In [63]:
# Return determinant of matrix
np.linalg.det(matrix)

0.0

# Getting the Diagonal of a Matrix

In [64]:
#Use diagonal:
# Load library

import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                 [2, 4, 6],
                 [3, 8, 9]])


# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

# Calculating the Trace of a Matrix

In [65]:
#Use trace:
# Load library

import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                 [2, 4, 6],
                 [3, 8, 9]])


# Return trace
matrix.trace()

14

# Finding Eigenvalues and Eigenvectors

In [66]:
#Use NumPy’s linalg.eig:
# Load library

import numpy as np
# Create matrix
matrix = np.array([[1, -1, 3],
                     [1, 1, 6],
                     [3, 8, 9]])


# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# View eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [67]:
# View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

# Calculating Dot Products

In [68]:
#Use NumPy’s dot:
# Load library

import numpy as np
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product

np.dot(vector_a, vector_b)

32

# Adding and Subtracting Matrices

In [69]:
# Load library
import numpy as np
# Create matrix

matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [70]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

# Multiplying Matrices

In [72]:
# Load library
import numpy as np
# Create matrix

matrix_a = np.array([[1, 1],
                    [1, 2]])
# Create matrix
matrix_b = np.array([[1, 3],
                     [1, 2]])

# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

# Inverting a Matrix

In [73]:
#Use NumPy’s linear algebra inv method:
# Load library

import numpy as np
# Create matrix
matrix = np.array([[1, 4],
                   [2, 5]])

# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

# Generating Random Values

In [74]:
# Load library
import numpy as np
# Set seed

np.random.seed(0)
# Generate three random floats between 0.0 and 1.0

np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [75]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [76]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [77]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [78]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)


array([1.47997717, 1.3927848 , 1.83607876])